create table employee_exp5_CSEA_38(emp_id int primary key,empname varchar(20),dept varchar(20),salary int );
desc employee_exp5_CSEA_38;
insert into employee_exp5_CSEA_38 values(1,'david smith','marketing',7500);
insert into employee_exp5_CSEA_38 values(2,'ayra','sales',8500);
insert into employee_exp5_CSEA_38 values(3,'charles brown','hr',9000);
insert into employee_exp5_CSEA_38 values(4,'oziya','production',5000);
insert into employee_exp5_CSEA_38 values(5,'ananya','sales',7000);
select * from employee_exp5_CSEA_38;
select * from employee_exp5_CSEA_38 where salary>7000;
update employee_exp5_CSEA_38 set salary=8300 where empname='david smith';
select * from employee_exp5_CSEA_38;
insert into employee_exp5_CSEA_38 values(6,'daniel harris','production',6700);
select * from employee_exp5_CSEA_38;
delete from employee_exp5_CSEA_38 where emp_id=3;
select * from employee_exp5_CSEA_38;
select empname from employee_exp5_CSEA_38 where not(empname like 'd%' OR empname  like 'o%');
select dept,sum(salary) as total_salary from employee_exp5_CSEA_38 group by dept;
update employee_exp5_CSEA_38 set salary=salary+(0.05*salary)where dept='production';
select * from employee_exp5_CSEA_38;
DELETE from employee_exp5_CSEA_38 where salary<7000;
select * from employee_exp5_CSEA_38;
select empname,salary from employee_exp5_CSEA_38 where salary=(select min(salary)from employee_exp5_CSEA_38);
update employee_exp5_CSEA_38 set salary=8200 where dept='marketing';
select * from employee_exp5_CSEA_38;
select empname from employee_exp5_CSEA_38 where empname like 'a%';
select empname from employee_exp5_CSEA_38 where empname like '%it%';
select UPPER(dept)from employee_exp5_CSEA_38;
select * from employee_exp5_CSEA_38 where dept like 'm%r%' and dept like '%ket%';
select distinct upper(reverse(dept))from employee_exp5_CSEA_38;
commit;
