select ceil(38.29) from dual;
select ceil(-38.9) from dual;
SELECT CEIL(38/3) FROM DUAL;
SELECT FLOOR(38.76) FROM DUAL;
SELECT FLOOR(-38.3) FROM DUAL;
SELECT FLOOR(38/4) FROM DUAL;
SELECT SQRT(38) FROM DUAL;
SELECT SQRT(2) FROM DUAL;
SELECT ABS(38.29) FROM DUAL;
SELECT ABS(-38.14) FROM DUAL;
SELECT ABS(-38) FROM DUAL;

SELECT SYSDATE AS NOW FROM DUAL;
SELECT TO_CHAR(SYSTIMESTAMP) FROM DUAL;
SELECT SYSTIMESTAMP FROM DUAL;
SELECT LEAST('JOSE','KEVIN','JO') FROM DUAL;
SELECT GREATEST('JOSE','KEVIN','JO') FROM DUAL;
SELECT LTRIM(' Trim me')FROM DUAL;
SELECT RTRIM(' I love India')FROM DUAL;

SELECT RPAD('JOSE',15,'/') FROM DUAL;
SELECT RPAD(123,6,'0') FROM DUAL;
SELECT REVERSE('uoyerawoholleh') FROM DUAL;
SELECT TO_CHAR('palindrome') FROM DUAL 
WHERE 'racecar'= REVERSE('racecar');
SELECT LENGTH('Oracle Database') FROM DUAL;
select concat(concat(concat(concat('oracle', ' '),
'sql'), ' '), concat(concat('is', ' '), 
concat('powerful', ' flexible'))) from dual;
SELECT CONCAT('Jose',' THOMAS') FROM DUAL;
SELECT SUBSTR('India is my country', 6, 3) FROM DUAL;
SELECT SUBSTR('JOSET', LENGTH('JOSET') / 2 , 3)
FROM DUAL;
SELECT SUBSTR('Substring', 1, 3) FROM DUAL;
commit;
